name: 'amocrm-integration'

services:
  fpm:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
      args:
        USER: ${AI_USER:-www-data}
    container_name: ${COMPOSE_PROJECT_NAME}-fpm
    depends_on:
      db:
        condition: service_healthy
    environment:
      DOMAIN: ${AI_DOMAIN:-ai.localhost}
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
      - app_var:/var/www/var
    networks:
      - backend-network

# one container - one process, all interactions through CLI-container
  cli:
    build:
      context: .
      dockerfile: docker/cli/Dockerfile
      args:
        USER: ${AI_USER:-www-data}
    container_name: ${COMPOSE_PROJECT_NAME}-cli
    environment:
      DOMAIN: ${AI_DOMAIN:-ai.localhost}
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor # share vendor with fpm
      - app_var:/var/www/var # share cache and logs with fpm
    networks:
      - backend-network

  db:
    image: postgres:${AI_PGSQL_VERSION:-16}-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-db
    environment:
      POSTGRES_DB: ${AI_PGSQL_DATABASE:-integration}
      POSTGRES_USER: ${AI_PGSQL_USERNAME:-integration}
      POSTGRES_PASSWORD: ${AI_PGSQL_PASSWORD:-integration}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d $$POSTGRES_DB" ]
      interval: 10s
    restart: unless-stopped
    tty: true
    ports:
      - "${AI_PGSQL_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-network

  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    depends_on:
      fpm:
        condition: service_started
    environment:
      DOMAIN: ${AI_DOMAIN:-ai.localhost}
    hostname: ${AI_DOMAIN:-ai.localhost}
    healthcheck:
      test: "curl -f http://$$DOMAIN"
      interval: 10s
    restart: unless-stopped
    tty: true
    ports:
      - "${AI_NGINX_PORT:-80}:80"
    volumes:
      - ./public:/var/www/public:ro
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    networks:
      - backend-network

volumes:
  vendor:
  app_var:
  db_data:

configs:
  nginx_config:
    file: ./docker/nginx/conf.d/default.conf

networks:
  backend-network:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME}-backend-network